@Library('nexus')
import com.johnreah.jenkins.Artifact

List<Artifact> artifacts = [
        new Artifact(groupId: "com.mycompany.app", artifactId: "my-app", packaging: "jar"),
        new Artifact(groupId: "com.google.collections", artifactId: "google-collections", packaging: "jar"),
        new Artifact(groupId: "commons-logging", artifactId: "commons-logging-api", packaging: "jar")
]

pipeline {
    agent {
        docker {
            image 'maven:3-alpine'
            args '-v /root/.m2:/root/.m2'
        }
    }
    stages {
//        stage('Build') {
//            steps {
//                sh 'mvn -B -DskipTests clean package'
//            }
//        }
//        stage('Test') {
//            steps {
//                sh 'mvn test'
//            }
//            post {
//                always {
//                    junit 'target/surefire-reports/*.xml'
//                }
//            }
//        }
//        stage('Deliver') {
//            steps {
//                sh './jenkins/scripts/deliver.sh'
//            }
//        }
        stage('Nexus') {
            steps {
                nexusFindArtifacts "http://172.17.0.2:8081/service/rest", artifacts
            }
        }
    }
}
